# Default values for osiris-dlt-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Instance: production 

UNIS:
  domain: "155.101.6.236"
  port: 8888 


replicaCount: 1

image:
  repository: miosiris/dltweb
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 42424

