# Default values for osiris-dlt-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Instance: global

UNIS:
  domain: localhost
  port: 9000


replicaCount: 1

image:
  repository: miosiris/dltweb
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 42424

