apiVersion: v1
kind: Service
metadata:
  name: {{ include "osiris-nmal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "osiris-nmal.name" . }}
    helm.sh/chart: {{ include "osiris-nmal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: port1
      protocol: TCP
      name: serv1
    - port: 8000
      targetPort: port2
      protocol: TCP
      name: serv2
    - port: 9001
      targetPort: port3
      protocol: TCP
      name: serv3
    - port: 42424
      targetPort: port4
      protocol: TCP
      name: serv4 
    - port: 6633
      targetPort: port5
      protocol: TCP
      name: serv5
  selector:
    app.kubernetes.io/name: {{ include "osiris-nmal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
